{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "abcp-agent.saName" . }}
  namespace: {{ include "abcp-agent.namespace" . }}
  labels:
    {{- include "abcp-agent.labels" . | nindent 4 }}
{{- end }}
